Repository hajke-gu/text-mod, pull requests merged in 2020-12, with the labels that each got.

#220 Feature sort symbol
  src/assets/sort_down_16x16.svg
  src/assets/sort_up_16x16.svg
  src/creator.js
  src/helper.js
  src/main.css
  src/main.js
  src/mod-manifest.json
  src/renderer.js
Labels: Acceptance criteria 6

#225 Update position of sort button
  src/main.css
Labels: bug

#239 Adds error if there is no content to be displayed.
  src/main.js
Labels: automerge
