Repository hajke-gu/text-mod, pull requests merged in 2020-10, with the labels that each got.

#35 Dynamic scrolling
  src/main.js
Labels: Acceptance Criteria 1, Acceptance criteria 2, Acceptance criteria 3

#38 Fixes printing of wrong text when clicking element
  src/main.js
Labels: Acceptance Criteria 1, Acceptance criteria 2, Acceptance criteria 3

#59 Removes rerendering of every div every time
  src/main.js
Labels: Acceptance criteria 3

#64 Fix bug when reading color of undefined, removes some print outs
  src/main.js
Labels: bug

#76 Fix de marking on click
  src/main.js
Labels: Acceptance criteria 4

#79 Modular text-card height.
  src/main.css
  src/main.js
Labels: Acceptance criteria 2

#89 Copy button icon
  src/assets/copy-icon.svg
  src/main.css
  src/main.js
Labels: Acceptance criteria 5

#91 Update sorting to work with expressions
  src/main.js
Labels: Acceptance criteria 6

#92 Moves the copy button the top right corner
  src/main.js
Labels: Acceptance criteria 5

#100 Marking opacity
  src/main.js
Labels: Acceptance criteria 4

#101 Many copy-button changes
  src/assets/copy-icon.svg
  src/assets/copy_16x16.svg
  src/main.css
  src/main.js
Labels: Acceptance criteria 5
