Repository hajke-gu/text-mod, pull requests merged in 2020-11, with the labels that each got.

#127 Error handling for multiple Axis-selection
  src/main.js
Labels: Acceptance Criteria 1, Acceptance criteria 6

#132 Feature multipile annotations
  src/main.css
  src/main.js
Labels: Acceptance criteria 11

#134 Add tooltip for annotations
  src/main.js
Labels: Acceptance criteria 11

#139 Fix bug, chrash when no annotation selected
  src/main.css
  src/main.js
Labels: bug

#140 Fix for marking
  src/main.js
Labels: Acceptance criteria 4

#141 Fixes small errorr message
  src/main.js
Labels: Acceptance criteria 4

#143 Fix for OSX -usage when doing marking
  src/main.js
Labels: Acceptance criteria 4

#147 Fixes marking for mac
  src/main.js
Labels: Acceptance criteria 4

#153 Bugfix scroll
  src/main.js
Labels: automerge

#181 Fixes marking for old scroll
  src/main.js
Labels: automerge, bug

#201 fix unittest 1
  puppeteer.js
Labels: automerge

#205 Adds functionality for bulk marking
  src/main.js
  src/renderer.js
Labels: automerge
